import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

/*
  Generated class for the CityDataProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class ZhuanyeDataProvider {

  zhuanyes: any[];

  constructor() {
    this.zhuanyes = [{
      "options": [{
          "text": "哲学",
          "value": "哲学"
      }, {
          "text": "经济学",
          "value": "经济学"
      }, {
          "text": "法学",
          "value": "法学"
      }, {
          "text": "教育学",
          "value": "教育学"
      }, {
          "text": "文学",
          "value": "文学"
      }, {
          "text": "历史",
          "value": "历史"
      }, {
          "text": "理学",
          "value": "理学"
      }, {
          "text": "工学",
          "value": "工学"
      }, {
          "text": "农学",
          "value": "农学"
      }, {
          "text": "医学",
          "value": "医学"
      }, {
          "text": "军事学",
          "value": "军事学"
      }, {
          "text": "管理学",
          "value": "管理学"
      }, {
          "text": "艺术学",
          "value": "艺术学"
      }]
  },{
      "options": [{
          "text": "哲学",
          "value": "哲学",
          "parentVal": "哲学"
      },{
          "text": "理论经济学",
          "value": "理论经济学",
          "parentVal": "经济学"
      },{
          "text": "应用经济学",
          "value": "应用经济学",
          "parentVal": "经济学"
      },{
          "text": "法学",
          "value": "法学",
          "parentVal": "法学"
      }, {
          "text": "政治学",
          "value": "政治学",
          "parentVal": "法学"
      },{
          "text": "社会学",
          "value": "社会学",
          "parentVal": "法学"
      }, {
          "text": "民族学",
          "value": "民族学",
          "parentVal": "法学"
      },{
          "text": "马克思主义理论",
          "value": "马克思主义理论",
          "parentVal": "法学"
      },{
          "text": "教育学",
          "value": "教育学",
          "parentVal": "教育学"
      },{
          "text": "心理学",
          "value": "心理学",
          "parentVal": "教育学"
      }, {
          "text": "体育学",
          "value": "体育学",
          "parentVal": "教育学"
      },{
          "text": "中国语言学",
          "value": "中国语言学",
          "parentVal": "文学"
      }, {
          "text": "外国语言文学",
          "value": "外国语言文学",
          "parentVal": "文学"
      },{
          "text": "新闻传播学",
          "value": "新闻传播学",
          "parentVal": "文学"
      },{
          "text": "历史学",
          "value": "历史学",
          "parentVal": "历史"
      },{
          "text": "数学",
          "value": "数学",
          "parentVal": "理学"
      },{
          "text": "物理学",
          "value": "物理学",
          "parentVal": "理学"
      },{
          "text": "化学",
          "value": "化学",
          "parentVal": "理学"
      }, {
          "text": "天文学",
          "value": "天文学",
          "parentVal": "理学"
      }, {
          "text": "地理学",
          "value": "地理学",
          "parentVal": "理学"
      }, {
          "text": "大气科学",
          "value": "大气科学",
          "parentVal": "理学"
      }, {
          "text": "海洋科学",
          "value": "海洋科学",
          "parentVal": "理学"
      }, {
          "text": "地球物理学",
          "value": "地球物理学",
          "parentVal": "理学"
      }, {
          "text": "地质学",
          "value": "地质学",
          "parentVal": "理学"
      }, {
          "text": "生物学",
          "value": "生物学",
          "parentVal": "理学"
      }, {
          "text": "系统科学",
          "value": "体统科学",
          "parentVal": "理学"
      }, {
          "text": "科学技术史",
          "value": "科学技术史",
          "parentVal": "理学"
      }, {
          "text": "力学",
          "value": "力学",
          "parentVal": "工学"
      }, {
          "text": "机械工程",
          "value": "机械工程",
          "parentVal": "工学"
      }, {
          "text": "光学工程",
          "value": "光学工程",
          "parentVal": "工学"
      }, {
          "text": "仪器科学与技术",
          "value": "仪器科学与技术",
          "parentVal": "工学"
      }, {
          "text": "材料科学与工程",
          "value": "材料科学与工程",
          "parentVal": "工学"
      }, {
          "text": "冶金工程",
          "value": "冶金工程",
          "parentVal": "工学"
      }, {
          "text": "动力工程及工程热物理",
          "value": "动力工程及工程热物理",
          "parentVal": "工学"
      }, {
          "text": "电气工程",
          "value": "电气工程",
          "parentVal": "工学"
      }, {
          "text": "电子科技与技术",
          "value": "电子科技与技术",
          "parentVal": "工学"
      }, {
          "text": "信息与通信工程",
          "value": "信息与通信工程",
          "parentVal": "工学"
      }, {
          "text": "控制科学与工程",
          "value": "控制科学与工程",
          "parentVal": "工学"
      }, {
          "text": "计算机科学与技术",
          "value": "计算机科学与技术",
          "parentVal": "工学"
      }, {
          "text": "建筑学",
          "value": "建筑学",
          "parentVal": "工学"
      }, {
          "text": "土木工程",
          "value": "土木工程",
          "parentVal": "工学"
      }, {
          "text": "水利工程",
          "value": "水利工程",
          "parentVal": "工学"
      }, {
          "text": "测绘科学与技术",
          "value": "测绘科学与技术",
          "parentVal": "工学"
      }, {
          "text": "化学工程与技术",
          "value": "化学工程与技术",
          "parentVal": "工学"
      }, {
          "text": "地质资源与地质工程",
          "value": "地质资源与地质工程",
          "parentVal": "工学"
      }, {
          "text": "矿业工程",
          "value": "矿业工程",
          "parentVal": "工学"
      }, {
          "text": "石油与天然气工程",
          "value": "石油与天然气工程",
          "parentVal": "工学"
      }, {
          "text": "纺织科学与工程",
          "value": "纺织科学与工程",
          "parentVal": "工学"
      }, {
          "text": "轻工技术与工程",
          "value": "轻工技术与工程",
          "parentVal": "工学"
      }, {
          "text": "交通运输工程",
          "value": "交通运输工程",
          "parentVal": "工学"
      }, {
          "text": "船舶与海洋工程",
          "value": "船舶与海洋工程",
          "parentVal": "工学"
      }, {
          "text": "航空宇航科学与技术",
          "value": "航空宇航科学与及时",
          "parentVal": "工学"
      }, {
          "text": "兵器科学技术",
          "value": "兵器科学技术",
          "parentVal": "工学"
      }, {
          "text": "核科学与技术",
          "value": "核科学与技术",
          "parentVal": "工学"
      }, {
          "text": "农业工程",
          "value": "农业工程",
          "parentVal": "工学"
      }, {
          "text": "林业工程",
          "value": "林业工程",
          "parentVal": "工学"
      }, {
          "text": "环境科学与工程",
          "value": "环境科学与工程",
          "parentVal": "工学"
      }, {
          "text": "生物医学工程",
          "value": "生物医学工程",
          "parentVal": "工学"
      }, {
          "text": "食品科学与工程",
          "value": "食品科学与工程",
          "parentVal": "工学"
      }, {
          "text": "作物学",
          "value": "作物学",
          "parentVal": "农学"
      }, {
          "text": "园艺学",
          "value": "园艺学",
          "parentVal": "农学"
      }, {
          "text": "农业资源利用",
          "value": "农业资源利用",
          "parentVal": "农学"
      }, {
          "text": "植物保护",
          "value": "植物保护",
          "parentVal": "农学"
      }, {
          "text": "畜牧学",
          "value": "畜牧学",
          "parentVal": "农学"
      }, {
          "text": "林学",
          "value": "林学",
          "parentVal": "农学"
      }, {
          "text": "水产",
          "value": "水产",
          "parentVal": "农学"
      }, {
          "text": "基础医学",
          "value": "基础医学",
          "parentVal": "医学"
      }, {
          "text": "临床医学",
          "value": "临床医学",
          "parentVal": "医学"
      }, {
          "text": "口腔医学",
          "value": "口腔医学",
          "parentVal": "医学"
      }, {
          "text": "公共卫生与预防医学",
          "value": "公共卫生与预防医学",
          "parentVal": "医学"
      }, {
          "text": "中医学",
          "value": "中医学",
          "parentVal": "医学"
      }, {
          "text": "基础中医学",
          "value": "基础中医学",
          "parentVal": "医学"
      }, {
          "text": "临床中医学",
          "value": "临床中医学",
          "parentVal": "医学"
      }, {
          "text": "中西医结合",
          "value": "中西医结合",
          "parentVal": "医学"
      }, {
          "text": "药学",
          "value": "药学",
          "parentVal": "医学"
      }, {
          "text": "中药学",
          "value": "中药学",
          "parentVal": "医学"
      }, {
          "text": "军事思想及军事历史",
          "value": "军事思想及军事历史",
          "parentVal": "军事学"
      }, {
          "text": "战略学",
          "value": "战略学",
          "parentVal": "军事学"
      }, {
          "text": "战役学",
          "value": "战役学",
          "parentVal": "军事学"
      }, {
          "text": "战术学",
          "value": "战术徐",
          "parentVal": "军事学"
      }, {
          "text": "军队指挥学",
          "value": "军队指挥学",
          "parentVal": "军事学"
      }, {
          "text": "军制学",
          "value": "军制学",
          "parentVal": "军事学"
      }, {
          "text": "军队政治工作",
          "value": "军队政治工作",
          "parentVal": "军事学"
      }, {
          "text": "军事后勤学与军事装备学",
          "value": "军事后勤学与军事装备学",
          "parentVal": "军事学"
      }, {
          "text": "管理科学与工程",
          "value": "管理科学与工程",
          "parentVal": "管理学"
      }, {
          "text": "工商管理",
          "value": "工商管理",
          "parentVal": "管理学"
      }, {
          "text": "农林经济管理",
          "value": "农林经济管理",
          "parentVal": "管理学"
      }, {
          "text": "公共管理",
          "value": "公共管理",
          "parentVal": "管理学"
      }, {
          "text": "图书馆、情报与档案管理",
          "value": "图书馆、情报与档案管理",
          "parentVal": "管理学"
      }, {
          "text": "艺术学",
          "value": "艺术学",
          "parentVal": "艺术学"
      }]
    }]
  }
}
